[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino

lib_deps =
  m5stack/M5Dial@^1.0.2
  lvgl/lvgl@^9.3.0
  emelianov/modbus-esp8266 @ ^4.1.0   ; obsahuje ModbusRTU/ModbusTCP, autor A. Emelianov

build_flags =
  -I include
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_USE_LOG=1
  -D LV_LOG_LEVEL=LV_LOG_LEVEL_INFO
  -D LV_FONT_MONTSERRAT_14=1
  -D LV_FONT_MONTSERRAT_16=1
  -D LV_FONT_MONTSERRAT_32=1
  -D LV_FONT_MONTSERRAT_48=1
  -w

monitor_speed = 115200
upload_speed = 115200
upload_flags = --no-stub